version: "5"
services:
  enggadda:
    image: mongo:latest
    container_name: "enggadda"
    ports:
      - 27017:27017
  springdockercompose:
    image: springdockercompose:latest
    container_name: "springdockercompose"
    ports:
      - 8080:8080
    links:
      - enggadda
